### PR TITLE
Added Gltf_Viewer files and its new model files.

### PR DESCRIPTION
**Pull request by n2k3**
Removed Debug_BVH_Intersection.html and its model file.

### CODE REVIEW

**Comment by n2k3** [comment]
I'm quite pleased with the [tweaked result](https://n2k3.github.io/glTF_Viewer.html), If I may say so myself ;)

If you want keep the Debug_BVH_Intersection.html, let me know, so I exclude it from the PR. But if you do please change the model used in that scene and remove the scene.gltf model file.

One thing I noticed is that with [backface culling on](https://github.com/erichlof/THREE.js-PathTracing-Renderer/blob/gh-pages/js/pathTracingCommon.js#L1016-L1018) (so, line 1018 uncommented) there are some light leaks:
backfacing light leaks I suppose the question is, is backface culling check from the camera's point of view?
If so, then yeah... it will introduce the problems highlighted above.

I would like to ask you to please go over the `Gltf_Viewer.glsl` shader file in-depth and give any feedback where you think improvements can be made. And also if you know how to solve certain TODO's in there please help out where you can. I guess we can keep this PR open to discuss and apply any changes until the problems have been resolved.

When I implement the drag & drop feature, I would like the included models to be removed again. As an example mode we could use the damaged helmet or the duck :)

Let me know what you think.

**Comment by erichlof** [comment]
Hi @n2k3 
The revised viewer is looking really good!  I will copy your code into my editor and play around with some of the settings and epsilons and see if I can get rid of some of those light leaks.  I will also look over the shader code carefully and see if I can spot any errors or optimization candidates - but from how it's running nicely, it looks really good so far!

About the old debug_intersection html file, that's fine - you can permanently remove that.  I will want to use your most updated version of the viewer on this repo going forward.  

Great work!  I'll let you know when I can look over everything.
Thanks,
-Erich

**Comment by erichlof** [comment]
@n2k3 
I cleaned up and updated the shader code.  You can find it [here](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)

Yes you might want to comment out the back-face culling inside pathTracingCommon, the BVH_TriangleIntersect() routine.  I also found this necessary in order to avoid the light leaks with this house model.  I also adjusted the epsIntersection to be higher.  I just realized while typing this that I should offset the eps intersection by the face normal instead of giving it a head start toward the sun direction - I'll try that soon and report back.

 The windows appear to be working but the color or dark tinting on the windows makes the sunlight that goes through the windows too dark in my opinion.  You might still try lightening the color to almost white, vec3(1.0, 1.0, 1.0) with maybe the red channel dialed down just a little less, 0.8 or so, for a greenish bluish tint.  But again, real house windows are pretty clear, almost white.  Unless the tinting is intentional like windows of a sports car, then it's totally fine I suppose.

 I have to go to work but I will make another post talking about the sunlight and other things like clouds and sky.  Let me know what you think so far.

**Comment by erichlof** [comment]
Hi, I'm back to discuss the directLighting and sky stuff.  About the directLighting, I noticed you tried directLightingSun and had to comment it out because it was crashing your browser gl context.  That was the original issue I ran into also a month or so ago when starting to work with more heavy models of 10,000 triangles and up.  With the older more simple scenes, the directLighting worked fine, and this is in fact the way most commercial renderers handle bright small light sources like the sun, or a spotlight or point light.  Without going too much into details, basically when a ray hits a diffuse surface, it sends out a shadowRay towards the sun or other bright small light source of our choosing.  If it hits nothing along the way, great, we light the surface.  If it runs into anything else however, the color comes back vec3(0), which is why they are nicknamed shadowRays.  They make everything converge much faster, but at a cost of sending double the amount of rays for diffuse surfaces.

This worked fine until the models got more complex, then the cost of sending out those extra shadowRays was really adding up.  Now on a modern expensive graphics card along with a C++ and CUDA or DirectX RTX environment, it wouldn't break a sweat, but with WebGL, javascript, glsl shaders, etc.,  the cost is just too much and the scene either won't compile or will run for just a few seconds before crashing.   A couple of months ago I thought I had hit a wall with browser path tracing and would never be able to render big models and small bright light sources, until I read a passage from Peter Shirley's Ray Tracing in One Weekend in which he casually mentions you can either do what the majority of programmers do, which is extra shadowRays, or you can just statistically send the original rays toward the light a little more often and down-weight them accordingly.  That one line changed my entire approach to all the demos, and that is how every demo is working now, especially the GLTF demos.  When I tried that alternate approach, the models all loaded just fine without crashing, no matter how large!  One of the tradeoffs though is getting the 'weight' variable to look good, which you noticed is an arbitrary number like 0.02.  My approach with this repo is to get things looking good and rendering fast in real time, not so much to be exactly physically correct (like energy conservation), so hence the 'magic' weight numbers.  For a more detailed analysis of how to down-weight sampled sunlight, see this [website](http://blog.hvidtfeldts.net/index.php/2015/01/path-tracing-3d-fractals/) in particular the section entitled "Direct Lighting / Next Event Estimation", which nicely explains the probability factors like arc angular diameters, etc.  All I know is that the weight has to be a small number because empirically what are the odds of a random ray exactly hitting the small Sun disk, vs. the whole other part of the sky?

Now about the clouds, I had wanted to add some procedural clouds to my outdoor demos so they would poof into existence and then poof out of existence like you see on sped-up footage of the sky.  Although they look good, they are very costly vs. just using a skybox or static HDR sky dome.  Therefore, for reflected surfaces like mirrors and glass, I had to 'cheat' a little by rendering the whole sky upfront and then rendering the 'precomputed' clouds inside the mirror or glass.  In reality you would have to re-render the clouds from the mirror's point of view to see what was behind your head, but the frame rate tanked when I tried it the 'correct' way, too much GPU divergence.  So in summation, if you really want accurate reflections no matter the angle, we might consider adding support for HDR sky backgrounds for the GLTF viewer, (which is what most ray/path tracers do anyway) rather than trying to build real volumetric clouds one pixel at a time.  That being said, if you look into the glass of the house, it does look pretty convincing, some of the sky you can see through the window on more face-on angles (which models reality exactly with the 1.5 index of refraction slightly bending the transparency rays), and you'll also see some reflected sky and sun in the parts of the glass that get reflected (from more shallow viewing angles due to the Fresnel effect, like a still lake).

Let me know what your goals are for the sky stuff and we can work from there.  :-)

**Comment by erichlof** [comment]
Ugh I feel like a dope, the epsIntersect wasn't even included in the code for the DIFF surface directLight branch!  The ray was getting nudged too far along the surface normal ('nl') from its origin, giving it too much of a head start, then of course it tunneled through walls and found the sun when it wasn't supposed too, lol!  When I added the eps, and turned back-face culling back on (which it really should be on all the time) the light leaking problem went away!  Here is the revised [shader](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)  This bug was driving me nuts, lol! ;-D

**Comment by n2k3** [comment]
I'll read through your feedback after I'm back from work today.

**Comment by n2k3** [comment]
Thanks for taking a look at the shader code, I've put the shader as pushed in my last commit live at: https://n2k3.github.io/glTF_Viewer.html

> That one line changed my entire approach to all the demos, and that is how every demo is working now, especially the GLTF demos. When I tried that alternate approach, the models all loaded just fine without crashing, no matter how large! One of the tradeoffs though is getting the 'weight' variable to look good, which you noticed is an arbitrary number like 0.02. My approach with this repo is to get things looking good and rendering fast in real time, not so much to be exactly physically correct (like energy conservation), so hence the 'magic' weight numbers.

Ah this explains it very well, thanks! I now understand the reasons why there are magic numbers, and what their trade offs are.

> So in summation, if you really want accurate reflections no matter the angle, we might consider adding support for HDR sky backgrounds for the GLTF viewer, (which is what most ray/path tracers do anyway) rather than trying to build real volumetric clouds one pixel at a time.

Using HDR sky backgrounds sound like a way better approach to clouds/background. This will reduce reality a bit but will improve performance and allows accurate environment reflections.

> Ugh I feel like a dope, the epsIntersect wasn't even included in the code for the DIFF surface directLight branch! The ray was getting nudged too far along the surface normal ('nl') from its origin, giving it too much of a head start, then of course it tunneled through walls and found the sun when it wasn't supposed too, lol!

Great work on finding this, really glad with the progress we're making, thanks!

---

As noted in commit message, using `r.direction` now for materials defined as REFR (so no refraction calculation), as `tdir` doesn't calculate the index of refraction correctly as shown in the two pictures below:
Just behind the glass window (1.0 ior of air):
lookingthroughair
Just in front of the (flat) glass window (1.5 ior of glass):
lookingthroughglass

**Comment by erichlof** [comment]
@n2k3 
Whoa that's weird about the curvature through the flat glass in your renderings.  Could you tell me what the geometry is for the windows?  Is it one pane of glass (like a single quad, or 2 triangles making a single rectangle shape), or is it like in reality, having 2 panes of glass, with a little air in between the 2 panes? The reason I ask is that all my demos have only dealt with 1 glass/dielectric surface, like a perfect hollow glass sphere, or a perfect body of water, with no real mathematical 'thickness' to the dividing surface edge - you're either on the outside of the object, or you're on the inside.  Now this works great with traditional raytracing technique (using the tdir, which stands for transmitted ray direction, btw).  But it may be giving errors when trying to go through 2 really close surfaces that both have 1.5 IoR.  In reality the ray would need to be refracted going from air to glass, then glass to the thin sliver of air between the 2 glass panes, then refracted going from thin sliver of air to 2nd glass, then finally back to air again (that's a lot of bounces!).

Yeah I agree that supporting static HDR would be a nice feature, especially for model viewing apps. I will look into that - I know how to handle it geometrically, but I'm not sure how to extract the right amount of energy from different parts of the sky.  I believe HDR has some kind of encoding with luminosity raised to some power, and not just straight ahead RGB like a regular texture would have.  

Other than these few minor issues, your model and demo look awesome!

**Comment by n2k3** [comment]
> Could you tell me what the geometry is for the windows? Is it one pane of glass (like a single quad, or 2 triangles making a single rectangle shape), or is it like in reality, having 2 panes of glass, with a little air in between the 2 panes?

The geometry consists of 12 triangles (so no quads) connected to 8 vertices per window. Where windows do not have multiple panes. Vertex normals are calculated by Three.js. The screenshot below displays two windows beside each other in wireframes viewed from an upper left angle.
glasspaneswireframe

> I know how to handle it geometrically, but I'm not sure how to extract the right amount of energy from different parts of the sky. I believe HDR has some kind of encoding with luminosity raised to some power, and not just straight ahead RGB like a regular texture would have.

Your assumption is correct, although I couldn't tell you how to get to the specific value in technical terms. But I'm pretty sure you can figure it out, if you can write this awesome PathTracing shader :1st_place_medal:

**Comment by erichlof** [comment]
@n2k3 
Ahh thanks for the picture.  It looks to me like there is thickness to the glass, although pretty narrow.  Maybe not 2 panes, but a front face (+Z) and a back face (-Z) separated by 2 very thin triangles on each side (+Y, -Y, +X, -X) of the flattened box shape.  When the refracted ray is trying to go through the small "thickness" (+Z to -Z) of that box, maybe it is getting messed up somehow, or there could be machine precision issues with the epsilon offset for such a tight region of space.
I'll play around with some of the values, but in the end, we might just be keeping what you have, the r.direction instead of tdir.

I'll let you know when I can study up on the HDR stuff.  Yeah it shouldn't be too hard to find an online resource outlining how you extract the luminosity data from such a file.

**Comment by erichlof** [comment]
@n2k3 
Success!  I finally figured out how to load an equi-rectangular HDR image, ray trace it as a background, extract the luminosity data for direct sunlight sampling, and then apply three.js's various optional tonemapping routines to bring the hdr data (greater than 1.0) back into the 0.0-1.0 RGB range for viewing on a computer screen.  Here are the links to all of the updated files:
[html](https://gist.github.com/erichlof/4ad31cd59674d5bb37e94b7fa0db550f)
[js](https://gist.github.com/erichlof/df50ff2ef076bab1f57cceebab67e4ec)
[RGBELoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/RGBELoader.js)
[shader](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)
[sample hdr](https://github.com/erichlof/THREE.js-PathTracing-Renderer/blob/gh-pages/textures/symmetrical_garden_2k.hdr)

Be sure to place the sample hdr file inside the 'textures' folder in your project directory so the new loading code inside the GltfViewer.js file can find it.  You can play around with the exposure setting, also defined at the top of the GltfViewer.js file (maybe an Exposure setting could replace the SunAngle slider in the gui menu, since the Sun location is 'set' in the hdr image file and cannot be changed).  

Speaking of sun direction, one issue with using hdr is that the sun direction of the file is unknown to the loader and path tracer.  I had to create a long red metal cylinder that extended to the sky just so I could visualize the angle at which to sample the direct sunlight inside the bounces loop of the path tracer.  Through trial an error I got the cylinder to 'touch' the sun spot on the large skydome and then used that normalized vec3 to put in the path tracer.  I only did 1 file so far, so if you change to something other than the symmetrical-garden hdr, then just be aware that we have to 're-find' the sun direction.  Eventually, we could have a list of all the files that you like, and their respective sun directions commented out beside them, or something like that.

Still no luck with refractive tdir, I'm not sure what's going on with the warping - let's just keep what you have, it looks great.  By the way I got all the HDR files from [here](https://hdrihaven.com/hdris/category/?c=skies) which does not require payment or licensing.  Feel free to tell me what background you want, which ones you like and don't like.  I don't have a preference, as long as there is a sun somewhere in the image.  :)

Edit: I forgot about RGBELoader.js located above - you definitely need that one in your js folder!

**Comment by erichlof** [comment]
@n2k3 
btw I put other HDR example files in this [folder](https://github.com/erichlof/THREE.js-PathTracing-Renderer/tree/gh-pages/textures) on my repo - there are a total of 5 to choose from.  Of course if you find another that you like on the internet, we can use that.  I just picked these because they were on a free website and they had some sun and clouds and mostly sky.  The perfect image would have mid-day sun, some white puffy clouds, and no ground, or minimal ground features, just sky. But I haven't found something like that as of yet.

**Comment by n2k3** [comment]
Hey Erich,

I've updated the PR with your changes, on which you did another great job! This cleans up the shader quite well, and the result is as good. And now there are correct reflections :)

Check it here: https://n2k3.github.io/glTF_Viewer.html

I've chosen the following HDR: https://assetstore.unity.com/packages/2d/textures-materials/sky/free-hdr-sky-61217
This one has some nice clouds in the sky but has no sun, this is fine for me. I decided to keep the sun angle property, to simulate a sun that generates shadows. Hmm... after thinking on this a bit, it seems I've incorrectly implemented the sun direction, as it's now getting the pixel based on the sun direction. While there is no sun at that position in the HDR image. I guess we could add another property to the menu that defines the color of the sun, instead of getting it from the HDR. But this will diminish the lighting information coming from the HDR.

The reason I added `skyLight` & `sunLight` intensity sliders is so that the user itself has more freedom over the lighting setup. If the user wants to have no direct sun light, it can be set to 0. The user can then increase the skyLight value to compensate and get a good result based on bounced light rays.

Some comparison screenshots, previous version (dynamic sun/sky/clouds):
previous

Updated version (HDR skybox): 
updated

A couple of things I noticed:
1. The previous version had way more blue in the parts that are in shadow. Compared to the updated version the difference is too big, the question is then, which one do you think better reflects reality? (Hmm, I now remember that I used a weight of 2.0 for any of light coming from the sky, so I guess this is part of the problem... [This is a picture with a weight of 1.0](https://user-images.githubusercontent.com/7542020/53305136-f55b9c80-387d-11e9-91a6-8e3be918ee2f.jpg))
1. I'm unsure if the light value retrieved from the HDR image is properly retrieved and/or applied. If you increase the hdrExposure value to 5, the skybox itself (when you look up) actually gets a lot brighter, but it feels as if the exposure value used for the PT has a lot less of an impact on the brightness of diffuse materials.

Let me know how you want to continue.

**Comment by erichlof** [comment]
@n2k3 
Hey everything is looking great!  Nice choice for the HDR image also, I like the puffy clouds!
About your 2 concerns, 

1. - Yes I believe the current result is following the behavior of real-world physical light correctly, even though it differs with respect to the amount of blue in the indirect illumination on the diffuse objects.  In the HDR you selected, if you look up and study the amount of clear sky, there is not much room - it's mostly white clouds.  Which is totally fine, but that will be the predominant color that is reflected on the house - white.  With my HDR choices and the old physical procedural sky, there is a much larger blue portion of the sky which is reflected in the objects below.

2. - Let me take a look and review how I am getting the power (or energy) amount out of the sky when a random diffuse ray hits it.  At least on my machine, when I dial up the energy with the sun or the sky HDR, the house gets brighter as it should.  Hmm... I'm just thinking, I bet the tone-mapper is capping the energy output.  Now without it, the sky becomes unbearable because the colors overflow - it looks a little weird.  But maybe the choice of the various tone mapping styles affects the total amount of output.  I'll mess around with some things and report back.  If all else fails, we can manually dial up the 'weight' value in the shader.  That will definitely make things brighter. :)

Again, looks great, thanks!  I'll let you know what I find out.

**Comment by erichlof** [comment]
Yep that was it - the Uncharted 2 tonemapper was limiting the power output (as it was designed to).  Try the Linear tonemapping option, then dial the sunlight intensity all the way down, and the sky all the way up.  The house will become washed out with white light - almost too much, but at least we know it's working.  :)

In the end, we may just want Linear tonemapping, because that allows the greatest range of light from dark (black) to over-saturated white.

As before, I have made some small changes to the shader.  Here is the new one:
[shader](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)

Let me know if you like being able to dial the light up and down that much.

**Comment by n2k3** [comment]
Yea you're right, tone-mapped exposure is better. I also fixed sun light not going through windows while taking the `sunLightIntensity` multiplier into account.

Check the updated result here: https://n2k3.github.io/glTF_Viewer.html

It wouldn't make sense why people would want over exposed images. And in that light (heh), would it possible to clamp the values of the skybox itself as well? I've tested multiplying the inverted hdrExposure value to the textData.rgb, this will render the skybox correctly, but reduces the amount of light in the scene as well...

One last problem I want to resolve before we can consider this PR complete. Using a non-default `sunAngle` value (for example `1.67`) results in blue sky light. This seems to be related to Get_HDR_Color() which is getting a pixel's color based on the sun direction. But since the image is mostly white it 'works'.
To solve this: I guess we could add another property to the menu that defines the color of the sun, instead of getting it from the HDR. This would result in lighting being combined from the sun color and the HDR image. Would you agree?

One last thing I noticed when setting both sky & sun light intensity to 0, there is still light (and a rather cool effect):
cool
This seems to be based on [these two lines](https://github.com/erichlof/THREE.js-PathTracing-Renderer/blob/4e8accadcc98981fe375683d9da2f859220c9667/shaders/Gltf_Viewer.glsl#L314-L315). Is this the intended behavior?

**Comment by erichlof** [comment]
Hi @n2k3 
I fixed that mysterious ghost light when all the lights are turned off.  I just forgot to add the skyLight multiplier.  Although the subtle light *is* cool, it was not really intended behavior, he he. 

[shader](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)

Yes I agree that there should be a color picker for the sun color. It would be nice, for instance, to lower the sun to just above the horizon, and then choose a reddish orange color.  If you can somehow get a simple rainbow slider added in, I'll be glad to hook it up to the uSunLightIntensity variable in the shader.  It should work if we just multiply the vec3 Sun color choice times the uSunLightIntensity float.

The new tone mapping option you chose looks real nice.  Yeah I don't know why people would want to over-expose the HDR image - it seems to get washed out and unrealistic looking.  But just to be on the conservative side, we probably should leave the exposure slider in there.  :)

**Comment by n2k3** [comment]
Hey @erichlof,

I've added the sun color as a property to the menu (and the hdr exposure is back too).
Check it out here: https://n2k3.github.io/glTF_Viewer.html

One last thing, I promise :)
Adding the `skyLightIntensity` multiplier fixes light going through refractive materials when both sun & sky intensity are `0`, but this introduces the problem that when viewing through a refractive material, the hdr sky is multiplied as well. And I can't think of a way to separate the two situations... In other words: multiplying by `skyLightIntensity` to get rid of the phantom light through glass, but NOT multiplying when looking to the sky through refractive materials (see picture below).
double hdr intensity through glass

Do you have any idea's on how to solve this?

**Comment by erichlof** [comment]
@n2k3 
Ahh yes I see the bug now too.  There's so many angles to think about in path tracing - I didn't see that one, ha ha.  Let me try a couple of things to hopefully fix it.  Will be back soon! :)

p.s. great job on adding the sun color and all the other gui controls - it's really shaping up nicely!

**Comment by erichlof** [comment]
@n2k3 
I'm back!  I think this covers all the situations :-D
[shader](https://gist.github.com/erichlof/2e6846a170db7407abc92b5a5c9c147e)

**Comment by n2k3** [comment]
Neat, thanks for the help!

Go ahead an merge this :+1: 
Based on this example I'll add drag & drop support.
I'll remove the default house model so that users can load their own glTF model(s). Maybe a drop-down in the menu to switch between the damaged helmet and the duck models.

P.S. maybe for convenience you can do this for future PR's:
https://help.github.com/en/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by erichlof** [comment]
@n2k3 
Everything looks great!  Merging...
Thanks for the 'committing changes to a fork' link - I was wondering if that was possible.  Even though I've been coding for many years, I'm still pretty much a newbie when it comes to GitHub, lol.   One of these days I need to go through the docs or watch a youtube tutorial on GitHub so I can at least get the basics down.  :)

Thanks for all your work on this PR!  In the coming days I'll create a link to your GLTF_Viewer on my README.md.  Yeah it would be nice to have a model picker, between helmet and duck for instance.  But that might call for a separate PR.  I would have to redo some of the shader code to load a different model/BVH on the fly while the demo is running at full speed.  It's possible, I just need to figure out the best/easiest way to get that functionality in, which might take more than a couple of days.

If you have any changes in the future just let me know, thanks! 
-Erich

**Pull request merged**
