### PR TITLE
Now handles submeshes.

### PR DESCRIPTION
**Pull request by n2k3**
Although this will only handle 1 level of submeshes, will have to make it recursive in the future to handle that. This fix makes loading the separate house model glTF files load correctly.

### CODE REVIEW

**Comment by erichlof** [comment]
Looks good! Thank you! I'm still recovering from being ill, but slowly starting to feel better. Excited about being able to load the GLTF files correctly! Thanks again

**Comment by n2k3** [comment]
You're welcome, and take your time :)
I'm now starting on a clean html file named glTF_Viewer.html while restructuring most code, when I'm satisfied with it, i'll make another pull request (this might take a couple of days though).

**Comment by n2k3** [comment]
I've uploaded my latest glTF Viewer here: https://n2k3.github.io/glTF_Viewer.html

One thing I've been wondering: is it possible to use multiple GPU's for this kind of workload?

And let me know what you think :)

**Comment by erichlof** [comment]
@n2k3 
The new viewer is great!  I like how you incorporated the natural sky and clouds into the background.  Also the GUI controls in the right top corner are handy.  When you're ready, I'll put a permanent link on my README.md front page to your GLTF viewer and I will give you credit in the description blurb above it.  Then, you can edit it any time you wish by just submitting a pull request and I will merge them right away.  One minor suggestion - maybe the windows should be a very light blue, like rgb 0.1, 0.5, 0.6 ,  or even more green and clear like 0.8, 0.9, 0.7.  The pure blue as it is now looks a little like blue plastic rather than window glass.  Just a suggestion :)

About the multiple GPU's, I'm not sure how that would work code-wise.  I know you can do that with CUDA  and OpenCL and the like, but I'm not sure about WebGL in the browser.  I have never had access to 2 GPU's in one system before.

Great work on the viewer! :)

**Comment by n2k3** [comment]
Worked on it a bit more, pretty close to drag & drop support for glTF models.

Can you check how [I've restructured the code](https://github.com/n2k3/THREE.js-PathTracing-Renderer/tree/glTFviewer), and if it's to your liking? So that maybe you can adopt the structure for all your demo's. It'll be a lot of work to convert all demo's, but after that I think it'll make the code more re-usable and better to manage.

I'll make a pull request once I've got my drag & drop ready (which I suspect will be ready at the end of this week). I'll also prepare a nicer house model, with some textures.

I think I've done a quick and dirty job of combining the shaders from multiple of your demo's. I'm still pretty new on how all this PT is actually working :) It would be appreciated if you could take a look at that once I'll make that pull request.

P.S. Nice progress on your [Animated BVH Model Demo](https://erichlof.github.io/THREE.js-PathTracing-Renderer/Animated_BVH_Model.html)! And great to see PBR material support :)
Quick question: would it be easy to toggle visibility for (separate) mesh objects? I suspect not because everything is combined before it was sent to the GPU.
Quick question 2: would it be possible (and better for performance) to use indexed geometry?

**Comment by erichlof** [comment]
Hi @n2k3 
Yes I like how you restructured the code so far.  One of the issues I was facing as the number of demos has been increasing in the last year, has been that there is always a lot of repeated code from .html file to .html file, like init three.js, making window resize handler, etc. - it's all the same no matter the demo.  Is it possible to have like I have in the shader section, where I type "include pathtracingmain" and it goes and finds that snippet and inserts it? With .js code I mean?  I suppose we could have a generic "function" for most repetitive tasks in a 'commonSetup.js' file, similar to pathtracingCommon.  That way, if I decide to change something about the way I handle init three.js, init data textures, handle window resize, etc., I could just update the commonSetup.js file and all the demos would pull from that.  Does that sound like a good way forward?
Once you make the pull request, I will go line by line through your shader code that you combined, just to make sure you didn't do any extra work during the tight path tracing loops.  But just glancing at it, it looks fine.

I really like the loading icon too while the model is loading - that is a nice addition!  
Yeah I'm real excited too about the progress on the Animated BVH.  I dreaded having to throw all the BVH builders away (that work just fine right now) in order to put a much more complicated LBVH that builds every frame just so you can move the model around.  I gladly found a way around that, and it works quite nicely for arbitrary translation, rotation, and uniform and non-uniform scaling (you can squash, stretch, and deform the model too, which is cool).  The best part is that the old BVH code can still do its thing and it is a high quality build, so that the least amount of triangles have to be checked.  Which is more than can be said for the complex LBVH that re-builds from scratch 60 times a second (you have to trade a little tracing efficiency quality for speed of build).
The remaining question is whether this technique that I'm exploring will work for a rigged GLTF model that loads an animation or multiple animations and that has a set of bones.  I'm investigating how three.js handles this because it seems there is a 4x4 matrix for each and every bone of an animated model, which can add up and deplete all your uniform space for the GPU.  So a 'bone' texture is apparently used, but I'm unsure how to extract from it what I need 60 times a second and use that to trace into the animating model.  It's definitely a learning experience, ha!

To question 1: yes you can simply add a visible uniform to each model and turn it on and off.  If it's off, the BVH loop would be skipped inside the shader. To question 2: I don't think it makes a difference in our path tracing case how the geometry is stored, indexed or non-indexed.  The BVH builder just needs the triangle vertex data and the associated material properties and has its own way of storing all that into a tightly packed texture.  I don't think it can squeeze the data any smaller into the BVH texture than it already is. And it doesn't affect it if the triangles are indexed or not.  But if you were just doing vanilla WebGL with three.js, then yes, the indexed geometry would be the clear choice.

**Comment by n2k3** [comment]
> Is it possible to have like I have in the shader section, where I type "include pathtracingmain" and it goes and finds that snippet and inserts it? With .js code I mean? I suppose we could have a generic "function" for most repetitive tasks in a 'commonSetup.js' file, similar to pathtracingCommon.

Like I've done [here](https://github.com/n2k3/THREE.js-PathTracing-Renderer/blob/glTFviewer/js/GltfViewer.js#L695) for glsl shaders or for JS functions specifically? For JS: scripts are inherited based on the order you include them in your html file. This is why GltfViewer.js [is included last](https://github.com/n2k3/THREE.js-PathTracing-Renderer/blob/glTFviewer/glTF_Viewer.html#L30), because it needs all the other scrips above it. Once loaded and [defined](https://github.com/n2k3/THREE.js-PathTracing-Renderer/blob/glTFviewer/js/GltfViewer.js#L102), you can [re-use](https://github.com/n2k3/THREE.js-PathTracing-Renderer/blob/glTFviewer/js/GltfViewer.js#L96) functions [anywhere](https://github.com/n2k3/THREE.js-PathTracing-Renderer/blob/glTFviewer/js/GltfViewer.js#L926) you want.

> I could just update the commonSetup.js file and all the demos would pull from that. Does that sound like a good way forward?

Yes is does ;)

> I don't think it makes a difference in our path tracing case how the geometry is stored, indexed or non-indexed. The BVH builder just needs the triangle vertex data and the associated material properties and has its own way of storing all that into a tightly packed texture.

Ah so the non-indexed geometry stored in the 2k texture is only created for use by the BVH builder and not used for the actual path trace rendering? Then it wouldn't give much performance benefit I agree, maybe a bit during creation of the BVH.

**Comment by erichlof** [comment]
@n2k3 
Yes like you did on the GltfViewer.js, but even a more generic file, like a commonFunctions.js  that contains nothing but the repeated code that every demo uses, like init, mouse pointer capture/mobile controls handlers, onWindowResize, even most of the animate() function could be reused, but maybe add a new updateUniforms() function inside the animate() function so that different demos could update different uniforms that they specifically need.  Each demo would have its own version of updateUniforms(), but all demos would call animate() from the commonFunctions.js file.  If I find some time I will sketch up a draft that outlines what that file would look like.

Yes there are two different 2k textures, one contains nothing but Axis-aligned bounding boxes (minCorner and maxCorner with connections to parent boxes and childA and childB boxes, and triangle numbers if the last smallest boxes are left with 1 triangle, so a leaf node (so yes I guess you could say the triangles are 'indexed' by their integer number, but not in the typical way that 3d engines do it).  The other 2k texture contains nothing but triangle vertex data.  The lookup number matches the lookup number on the box 2k texture, so while tracing through the boxes, if the ray hits a leaf node box, it goes and uses the same index (uv) on the triangle 2k texture, which gives it that exact triangle's 3 vertices, color, material, normal, etc..  Some tracing coders mix the triangle data and the bounding box data into 1 large texture, but I found it more intuitive to separate the concerns and just trace into nothing but boxes on 1 texture, and lookup nothing but triangles on the other texture.

**Comment by erichlof** [comment]
Hi @n2k3 
Just a quick update:  I started out to do a small outline to common.js and ended up refactoring the entire engine!  I followed your example (thanks for pointing the way forward), and I separated concerns with shader .glsl files, .css file, app.js-type file, and commonFunctions.js file that contains repeated code from demo to demo.  The index.html file is now just bare-bones, like you have in your fork.   I updated the old Geometry_Showcase demo to use all of these new files.  I have to work now, but I will post everything tonight!  Then I can start converting all the demos.  I can even help you convert your GLTF viewer to be inline with my big refactor.  But the point is that the code will be much more manageable, with a smaller codebase, and more reusable!  :-)

**Comment by erichlof** [comment]
@n2k3 
Good news, I located the source of the clipping problem and therefore we no longer need the magic 65.0 number that was added to the gltf BVH intersection routine.  That magic number was a band-aid for a wound that didn't need to be there, lol!  I followed it all the way back to my individual AABB ray intersect function inside pathTracingCommon.js .  

Turns out I was erroneously returning the inside back of the bounding boxes sometimes, (t1 of the ray), when what needed to happen all along is I should have been returning only t0, the first intersection, or the front of each box closest to the viewer. 
Here are the small [changes](https://github.com/erichlof/THREE.js-PathTracing-Renderer/commit/a3343e630fd0ffd067a5275fb6dd4acd8d282baf#diff-6a3b6e895803ee329187047c54fa5c1c)

 BVH intersection has different needs than rendering and shading.  I had copied the BVH routine from the old rendering ray-box intersection routine, which does indeed need the inside back of boxes, because what if you are inside a big box, like a room shape, etc..  The BVH routine shouldn't care about that I realize now, it only needs to know if a box was hit from the outside, and only the first ray intersection is supposed to be utilized.  This correction not only resolves all model triangles correctly with no more erroneous clipping, but it also sped up the frame rate!  

Would you like to maybe copy my current pathTracingCommon.js from my repo and replace yours?  Also, you should copy and replace the BVH routine, as I have updated my copy of your shader here:
[new BVH routine](https://github.com/erichlof/THREE.js-PathTracing-Renderer/blob/gh-pages/Debug_BVH_Intersection.html#L201-L279)

It starts with the line "while (true)"
Although my copy of your shader is probably out-of-date by now.  But at least you will have the correct optimized version of the BVH intersection routine to work with moving forward.

I have updated all of the demos to the new format, except your old version of the GLTF-Viewer.  When you're ready, I will try to incorporate your updated code into my codebase and make a dedicated demo on my repo with credit to you.

**Comment by n2k3** [comment]
> Good news, I located the source of the clipping problem and therefore we no longer need the magic 65.0 number that was added to the gltf BVH intersection routine. That magic number was a band-aid for a wound that didn't need to be there, lol!

Great find!

Right now I'm removing pieces of the combined shader that aren't used, when that's finished I'm ready to make the pull request. Then you can apply your code refactor and fix any possible last bugs from there. And then I'll continue by adding drag and drop support.

**Pull request merged**
